services:

  mysql:
    image: mysql:8.0
    container_name: ait-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Ashubhor@6262
      MYSQL_DATABASE: jrtp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: ait-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql

volumes:
  mysql_data:
